--********************************************************************
--
-- Copyright © 2025-2026 Dankest, LLC
-- Based on XChain Platform by Dankest, LLC - https://dankest.llc
--
-- SPDX-License-Identifier: AGPL-3.0-or-later
--
-- This file is part of XChain Platform. Licensed under the GNU Affero
-- General Public License v3.0 or later; see LICENSE.md. A commercial
-- license (without AGPL source-disclosure terms) is available -
-- contact legal@dankest.llc.
--
--********************************************************************

-- xchain:migration mode=auto
-- (auto: a lossless column widening from TEXT to MEDIUMTEXT. Safe to apply on a
--  running decoder; no data conversion, no backfill.)
-- Migration: events.data  TEXT (64KB)  ->  MEDIUMTEXT (16MB).
--
-- WHY
-- ---
-- verifyReorg serializes the list of rolled-back blocks into a single REORG event
-- row (events.data). Each entry is ~100 bytes, so a reorg deeper than ~650 blocks
-- (e.g. the node-tip-regression / misconfigured-node walks) overflows a TEXT
-- column and the INSERT fails, silently losing the only audit record of which
-- blocks were rolled back. transactions.data and mempool_transactions.data are
-- already MEDIUMTEXT; this aligns events.data with them. Fresh installs already
-- get MEDIUMTEXT from src/sql/events.sql, so on those this migration is a no-op.
--
-- IDEMPOTENT: re-applying MODIFY ... MEDIUMTEXT on an already-widened column is a
-- no-op, and the schema_migrations ledger records it once per DB so it never
-- re-runs regardless. Applies automatically at decoder startup.
--
-- Follower ordering note: xchain-sync replicates the decoder DB to validators.
-- Followers run the same auto migration on startup, so the column widens fleet-wide
-- before replication traffic arrives. However, a follower that is already running
-- and has NOT yet been restarted (i.e. the migration has not applied) will silently
-- truncate any oversized REORG event row received via INSERT IGNORE, because the
-- column is still TEXT on that node. The truncated row carries no error; the sync
-- client continues normally. Impact is low (events is operational audit, not
-- consensus state, and >64KB REORG rows require a reorg deeper than ~650 blocks),
-- but operators should restart all followers promptly after deploying this migration
-- so the column widens before any such event can arrive.

ALTER TABLE events MODIFY COLUMN data MEDIUMTEXT;
