'use strict';

// Copyright © 2025-2026 Dankest, LLC
// Based on XChain Platform by Dankest, LLC - https://dankest.llc
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file is part of XChain Platform. Licensed under the GNU Affero
// General Public License v3.0 or later; see LICENSE.md. A commercial
// license (without AGPL source-disclosure terms) is available -
// contact legal@dankest.llc.

// THE REST OF THE WHOLE-BATCH-REJECTION CLASS.
//
// The indexer rejects a BATCH as ONE record for several causes, and when it does, NOT ONE of
// its sub-commands runs. The decoder's capture kept reading the siblings anyway, so a
// dispenser registers here and nowhere else and payments to it are classified against a
// dispenser that never settles. batchSubCommandNameGate.test.js closed the one cause the
// decoder could prove on its own evidence (the EMPTY action name); this file closes the ones
// that became provable once the indexer's cap tables were vendored canonically
// (src/protocol/indexerBatchLimits.js, generated by test/tools/sync-batch-limits.js).
//
// THE DIRECTION OF ERROR IS NOT SYMMETRIC and every test here is written around that:
//   * OVER-capture (capture where the indexer rejects) is today's defect and is SAFE.
//   * UNDER-capture (suppress where the indexer dispatches) means a real settlement output is
//     never persisted, so a real payment is never recognised. It is the money-bearing
//     direction and it is what the "does NOT suppress" controls below exist to catch.
//
// The named trap: after BATCH_ISSUANCE_LIMITS arms, the dotted-TICK exemption makes ONE
// parent plus MANY dotted children a VALID batch. A decoder naively mirroring the pre-flag
// `ISSUE: 1` cap would suppress exactly those - under-capture, on the feature the flag ships.
// `the dotted-TICK exemption ...` cases below are that control, at both the helper and the
// block-loop level, and the real-corpus case measures how common the shape is.

const assert = require('assert');
const path   = require('path');

const { captureCommands,
        hasProvablyRejectedBatch,
        subCommandLimitKey,
        subCommandTick,
        maxIdenticalMintTicks,
        isLegacyActionFormat,
        COMMAND_LIMIT,
        CHILD_ISSUE_KEY } = require('../../src/batchSubCommandCapture.js');
const ACTION_ALIASES = require('../../src/actionAliases.js');
const { SOURCE, SELLER, CHANGE, ORACLE, T0,
        BELOW_GATE, ABOVE_GATE, runOne } = require('../helpers/batchCaptureHarness.js');

const CORPUS = require('../fixtures/regtestBatchCorpus.json');

const reject = (subCommands) => hasProvablyRejectedBatch(subCommands, ACTION_ALIASES);

// COINPAY|VERSION|ORDER_ACTION_INDEX - the sub-command whose presence makes capture happen at
// all, so it is the sibling every "does this batch capture?" case is built around.
const COINPAY = 'COINPAY|0|101';
const EXP_LATE = T0 + 900000;
// DISPENSER|0|GIVE_COIN|GIVE_TICK|GIVE_AMOUNT|GIVE_OWNERSHIP|GIVE_ESCROW|GET_COIN|GET_TICK|
//   GET_AMOUNT|GET_ADDRESS|FIAT_CODE|FIAT_AMOUNT|ORACLE_ADDRESS|EXPIRATION
const CREATE = ['DISPENSER', '0', 'BTC', 'TICK', '1', '', '10', 'BTC', '', '0',
                '', 'USD', '', ORACLE, String(EXP_LATE)].join('|');

const SETTLEMENTS = [
    { destinationAddress: SELLER, vout: 0, amount: '1.00000000' },
    { destinationAddress: CHANGE, vout: 1, amount: '5.00000000' },
];

const addressesOf = (rows) => rows.map(o => o.destinationAddress).sort();
const batchOf = (commands) => 'BATCH|0|' + commands.join(';');
// n SENDs, the cheapest filler command that trips no cap of its own.
const filler = (n) => Array.from({ length: n }, (_, i) => 'SEND|0|BTC|TICK|1|addr' + i);

describe('BATCH whole-batch rejection: the rest of the class', function () {
    this.timeout(0);

    // -------------------------------------------------------------------------------------
    describe('the global command cap', function () {

        it('is pinned to 250 HERE, not only against the sibling', function () {
            // Every other case in this describe reads COMMAND_LIMIT from the vendored module,
            // so a corrupted vendored value would move the tests along with the code and prove
            // nothing. This is the literal pin: it is the only thing in this file that still
            // has teeth on a checkout with no sibling indexer, where the drift tier skips.
            assert.strictEqual(COMMAND_LIMIT, 250);
        });

        it('does not suppress a batch AT the cap', function () {
            const commands = [COINPAY].concat(filler(COMMAND_LIMIT - 1));
            assert.strictEqual(commands.length, COMMAND_LIMIT);
            assert.strictEqual(reject(commands), false,
                'the indexer rejects on `> commandLimit`, so exactly the cap is accepted');
        });

        it('suppresses a batch ONE command over the cap', function () {
            const commands = [COINPAY].concat(filler(COMMAND_LIMIT));
            assert.strictEqual(commands.length, COMMAND_LIMIT + 1);
            assert.strictEqual(reject(commands), true);
        });

        it('counts EMPTY elements toward the cap, as the raw split does there', function () {
            // The indexer caps `String(TX_DATA).split(';').length` after the prefix strip,
            // empties included. A batch padded to over-cap with bare ';' is over-cap.
            const commands = filler(COMMAND_LIMIT).concat(['']);
            assert.strictEqual(reject(commands), true);
        });

        it('captures nothing through the real block loop for an over-cap batch', async () => {
            const decoder = await runOne(batchOf([COINPAY].concat(filler(COMMAND_LIMIT))),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(decoder.captured, [],
                'every sub-command of an over-cap batch is dead, including the COINPAY');
        });

        it('still captures for the SAME batch one command shorter', async () => {
            const decoder = await runOne(batchOf([COINPAY].concat(filler(COMMAND_LIMIT - 1))),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(addressesOf(decoder.captured), [CHANGE, SELLER].sort(),
                'the pair is the evidence: one case alone cannot tell suppression from a ' +
                'harness that never captures anything');
        });
    });

    // -------------------------------------------------------------------------------------
    describe('a nested BATCH', function () {

        it('suppresses the whole view, because actionLimits.BATCH is 0', function () {
            assert.strictEqual(reject([COINPAY, 'BATCH|0|SEND|0|BTC|TICK|1|addr']), true);
        });

        it('is rejected in BOTH flag states, which is why no flag reasoning is needed', function () {
            // BATCH:0 lives in the indexer's UNGATED actionLimits table, so this holds below
            // BATCH_ISSUANCE_LIMITS too. The vendoring test asserts that placement.
            const { ACTION_LIMITS } = require('../../src/protocol/indexerBatchLimits.js');
            assert.strictEqual(ACTION_LIMITS.BATCH, 0);
        });

        it('captures nothing through the real block loop, sibling COINPAY included', async () => {
            const decoder = await runOne(batchOf(['BATCH|0|SEND|0|BTC|TICK|1|a', COINPAY]),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(decoder.captured, []);
        });

        it('registers NO dispenser when a nested BATCH kills the batch around it', async () => {
            const decoder = await runOne(batchOf([CREATE, 'BATCH|0|SEND|0|BTC|TICK|1|a']),
                ABOVE_GATE);
            assert.strictEqual(decoder.model.insertCalls, 0,
                'the indexer runs no sub-command here, so a dispenser registered by the ' +
                'decoder alone would classify payments against a dispenser that never settles');
        });

        it('still registers the SAME create without the nested BATCH', async () => {
            const decoder = await runOne(batchOf([CREATE]), ABOVE_GATE);
            assert.strictEqual(decoder.model.insertCalls, 1);
        });
    });

    // -------------------------------------------------------------------------------------
    describe('the per-ACTION ISSUE cap, and the dotted-TICK exemption that is the trap', function () {

        it('suppresses two TOP-LEVEL (undotted) ISSUEs', function () {
            assert.strictEqual(reject([COINPAY, 'ISSUE|0|AAA|1000', 'ISSUE|0|BBB|1000']), true);
        });

        it('does NOT suppress one parent plus MANY dotted children', function () {
            // The whole reason this row could not be built naively. Post-flag this batch is
            // VALID, so suppressing it would be under-capture on the feature the flag ships.
            const children = Array.from({ length: 50 }, (_, i) => 'ISSUE|0|JDOG.' + (i + 1) + '|1');
            assert.strictEqual(reject([COINPAY, 'ISSUE|0|JDOG|1000'].concat(children)), false);
        });

        it('does NOT suppress a batch of dotted children with no parent at all', function () {
            const children = Array.from({ length: 8 }, (_, i) => 'ISSUE|0|JDOG.' + (i + 1) + '|1');
            assert.strictEqual(reject([COINPAY].concat(children)), false);
        });

        it('counts caret TICKs TOP-LEVEL, so two of them suppress', function () {
            // ^<id>[.<n>] is an id reference whose dot is a decimal, never a namespace
            // separator, so the exemption does not apply and the cap of 1 bites.
            assert.strictEqual(reject(['ISSUE|0|^614.1|1', 'ISSUE|0|^614.2|1']), true);
            assert.strictEqual(subCommandLimitKey('ISSUE|0|^614.5|1', ACTION_ALIASES), 'ISSUE');
        });

        it('counts a TICK-less ISSUE TOP-LEVEL: exemption needs positive evidence', function () {
            assert.strictEqual(subCommandLimitKey('ISSUE|0', ACTION_ALIASES), 'ISSUE');
            assert.strictEqual(reject(['ISSUE|0', 'ISSUE|0|BBB|1']), true);
        });

        it('classifies a LEGACY no-VERSION dotted ISSUE as a child, not as top-level', function () {
            // normalizeSubAction splices the implied VERSION 0 for BTNS-style params, which is
            // what puts TICK at params[1]. Reading params[1] without that injection would see
            // the AMOUNT, find no dot, call the child top-level and SUPPRESS a valid batch.
            assert.strictEqual(isLegacyActionFormat(['JDOG.1', '1000']), true);
            assert.strictEqual(subCommandLimitKey('ISSUE|JDOG.1|1000', ACTION_ALIASES), CHILD_ISSUE_KEY);
            assert.strictEqual(reject(['ISSUE|JDOG|1000', 'ISSUE|JDOG.1|1000']), false);
        });

        it('captures nothing through the real block loop for two undotted ISSUEs', async () => {
            const decoder = await runOne(batchOf([COINPAY, 'ISSUE|0|AAA|1000', 'ISSUE|0|BBB|1000']),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(decoder.captured, []);
        });

        it('STILL CAPTURES for one parent plus fifty children (the money-bearing control)', async () => {
            const children = Array.from({ length: 50 }, (_, i) => 'ISSUE|0|JDOG.' + (i + 1) + '|1');
            const decoder = await runOne(batchOf([COINPAY, 'ISSUE|0|JDOG|1000'].concat(children)),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(addressesOf(decoder.captured), [CHANGE, SELLER].sort(),
                'the indexer dispatches this batch; suppressing it would drop a real ' +
                'settlement output, which is the failure this whole row is written against');
        });
    });

    // -------------------------------------------------------------------------------------
    describe('the gated DEPLOY cap', function () {

        it('does not suppress a single DEPLOY', function () {
            assert.strictEqual(reject([COINPAY, 'DEPLOY|0|code']), false);
        });

        it('suppresses two DEPLOYs', function () {
            assert.strictEqual(reject([COINPAY, 'DEPLOY|0|a', 'DEPLOY|0|b']), true);
        });

        it('captures nothing through the real block loop for two DEPLOYs', async () => {
            const decoder = await runOne(batchOf([COINPAY, 'DEPLOY|0|a', 'DEPLOY|0|b']),
                ABOVE_GATE, { outputs: SETTLEMENTS });
            assert.deepStrictEqual(decoder.captured, []);
        });
    });

    // -------------------------------------------------------------------------------------
    describe('the MINT cap, mirrored only as far as it is provable', function () {

        it('suppresses two MINTs naming the SAME literal TICK', function () {
            assert.strictEqual(reject([COINPAY, 'MINT|0|PEPE|1|addr', 'MINT|0|PEPE|2|addr']), true);
        });

        it('does NOT suppress two MINTs naming DIFFERENT literal TICKs', function () {
            // They may still be one token (`JDOG` and `^614` can resolve to the same id), and
            // the indexer would then reject - but the decoder cannot resolve ticks, so it
            // stays silent rather than guessing toward suppression.
            assert.strictEqual(reject([COINPAY, 'MINT|0|PEPE|1|addr', 'MINT|0|^614|2|addr']), false);
        });

        it('trims the TICK the same way the indexer does before comparing', function () {
            assert.strictEqual(subCommandTick('MINT', 'MINT|0| PEPE |1|addr'), 'PEPE');
            assert.strictEqual(reject(['MINT|0|PEPE|1|addr', 'MINT|0| PEPE |2|addr']), true);
        });

        it('buckets two TICK-less MINTs together, as the unresolved bucket does there', function () {
            assert.strictEqual(subCommandTick('MINT', 'MINT|0'), '');
            assert.strictEqual(reject(['MINT|0', 'MINT|0']), true);
        });

        it('is a lower bound on maxMintsPerDistinctTick, never an upper one', function () {
            assert.strictEqual(maxIdenticalMintTicks(['A', 'B', 'A', 'C']), 2);
            assert.strictEqual(maxIdenticalMintTicks(['A', 'B', 'C']), 1);
            assert.strictEqual(maxIdenticalMintTicks([]), 0);
            // Untrusted wire strings must not read as present on an object prototype.
            assert.strictEqual(maxIdenticalMintTicks(['__proto__', 'constructor']), 1);
        });
    });

    // -------------------------------------------------------------------------------------
    describe('names are alias-expanded before the tally, as the indexer counts them', function () {

        it('counts a sub-command under its CANONICAL name', function () {
            const table = Object.assign({}, ACTION_ALIASES, { XFER: 'DEPLOY' });
            assert.strictEqual(hasProvablyRejectedBatch(['DEPLOY|0|a', 'XFER|0|b'], table), true,
                'the indexer tallies the alias-expanded name, so two DEPLOYs spelled two ways ' +
                'break the cap there');
            assert.strictEqual(hasProvablyRejectedBatch(['DEPLOY|0|a', 'XFER|0|b'], ACTION_ALIASES), false,
                'and under the REAL table XFER is not an alias, so nothing moves today');
        });

        it('reads only OWN properties of the alias table', function () {
            assert.strictEqual(hasProvablyRejectedBatch(['constructor|0|a'], ACTION_ALIASES), false);
            assert.strictEqual(hasProvablyRejectedBatch(['toString|0|a'], ACTION_ALIASES), false);
        });
    });

    // -------------------------------------------------------------------------------------
    describe('what is NOT mirrored stays captured, deliberately', function () {

        it('does not suppress an UNREGISTERED action name', function () {
            // A vendored name list is not closed under registry growth, so a stale decoder
            // would suppress batches the indexer dispatches. Over-capture is the safe
            // direction and is left open; see hasProvablyRejectedBatch.
            assert.strictEqual(reject([COINPAY, 'NOT_AN_ACTION|0|x']), false);
            assert.strictEqual(reject([COINPAY, 'issue|0|AAA|1']), false);
        });

        it('does not suppress a batch whose SOURCE might be sleeping', function () {
            // Address-sleep state lives in the indexer database and is not derivable from the
            // transaction, so there is nothing here to mirror.
            assert.strictEqual(reject([COINPAY, 'SEND|0|BTC|TICK|1|addr']), false);
        });

        it('leaves a lowercase ISSUE pair uncapped, because the indexer tallies case-sensitively', function () {
            // `issue` is not the key 'ISSUE', so no cap applies there either; the batch dies on
            // the activation scan instead, which is the cause deliberately not mirrored.
            assert.strictEqual(subCommandLimitKey('issue|0|AAA|1', ACTION_ALIASES), 'issue');
            assert.strictEqual(reject(['issue|0|AAA|1', 'issue|0|BBB|1']), false);
        });
    });

    // -------------------------------------------------------------------------------------
    describe('BELOW the gate nothing moves', function () {

        it('leaves the command view as the legacy top-level string', function () {
            const over = batchOf([COINPAY].concat(filler(COMMAND_LIMIT)));
            assert.deepStrictEqual(captureCommands(over, 'mainnet', 4000000000), [over]);
            const nested = batchOf([COINPAY, 'BATCH|0|SEND|0|a']);
            assert.deepStrictEqual(captureCommands(nested, 'mainnet', 4000000000), [nested]);
        });

        it('captures nothing for any of these batches, exactly as the live fleet wrote it', async () => {
            for (const commands of [[COINPAY].concat(filler(COMMAND_LIMIT)),
                                    [COINPAY, 'BATCH|0|SEND|0|a'],
                                    [COINPAY, 'ISSUE|0|AAA|1', 'ISSUE|0|BBB|1'],
                                    [COINPAY, 'ISSUE|0|JDOG|1', 'ISSUE|0|JDOG.1|1']]) {
                const decoder = await runOne(batchOf(commands), BELOW_GATE, { outputs: SETTLEMENTS });
                assert.deepStrictEqual(decoder.captured, [],
                    'below the gate a BATCH captures nothing at all, which is the byte-identity ' +
                    'a from-genesis re-decode of pre-flag-day history depends on');
            }
        });

        it('a TOP-LEVEL COINPAY is untouched below AND above the gate', async () => {
            for (const venue of [BELOW_GATE, ABOVE_GATE]) {
                const decoder = await runOne(COINPAY, venue, { outputs: SETTLEMENTS });
                assert.deepStrictEqual(addressesOf(decoder.captured), [CHANGE, SELLER].sort(),
                    'nothing in this change may reach a transaction that is not a BATCH');
            }
        });
    });

    // -------------------------------------------------------------------------------------
    // The real thing, not a fixture written to match the code: every DISTINCT `BATCH|%`
    // payload on the live BTC regtest decoder chain at the time of writing.
    describe('the real on-chain corpus', function () {

        it('is a real corpus, not an empty one', function () {
            assert.ok(CORPUS.length >= 55, 'corpus shrank: re-pull it rather than lowering this');
            assert.ok(CORPUS.every(d => typeof d === 'string' && d.startsWith('BATCH|')));
        });

        it('suppresses only batches the indexer really rejects whole, and says how many', function () {
            const suppressed = [];
            const captured   = [];
            for (const payload of CORPUS) {
                const view = captureCommands(payload, 'regtest', T0);
                (view.length === 0 ? suppressed : captured).push(payload);
            }
            // Every suppressed payload must carry a cause this module can name. If one ever
            // cannot, the mirror has started suppressing on something it has not proved,
            // which is the money-bearing direction.
            for (const payload of suppressed) {
                const subCommands = payload.slice('BATCH|0|'.length).split(';');
                const causes = [];
                if (subCommands.length > COMMAND_LIMIT)                       causes.push('command cap');
                if (subCommands.some(c => c.split('|')[0] === ''))            causes.push('empty name');
                if (subCommands.some(c => c.split('|')[0] === 'BATCH'))       causes.push('nested BATCH');
                const top = subCommands.filter(c =>
                    subCommandLimitKey(c, ACTION_ALIASES) === 'ISSUE').length;
                if (top > 1)                                                  causes.push('ISSUE cap');
                assert.ok(causes.length > 0,
                    'suppressed a payload with no provable cause: ' + payload.slice(0, 120));
            }
            assert.strictEqual(suppressed.length + captured.length, CORPUS.length);
            assert.ok(suppressed.length > 0 && captured.length > 0,
                'a corpus that is all one way proves nothing about the other');
        });

        it('never suppresses a batch whose ISSUEs are all dotted children', function () {
            // The under-capture control against real payloads: the exemption is what most of
            // this corpus depends on, so a naive `ISSUE: 1` mirror would suppress them.
            let exempted = 0;
            for (const payload of CORPUS) {
                const subCommands = payload.slice('BATCH|0|'.length).split(';');
                const keys = subCommands.map(c => subCommandLimitKey(c, ACTION_ALIASES));
                const children = keys.filter(k => k === CHILD_ISSUE_KEY).length;
                const top      = keys.filter(k => k === 'ISSUE').length;
                if (children < 1 || top > 1) continue;
                exempted++;
                if (subCommands.length > COMMAND_LIMIT || keys.includes('')) continue;
                assert.strictEqual(captureCommands(payload, 'regtest', T0).length,
                    subCommands.length,
                    'a many-child batch must keep its full command view: ' + payload.slice(0, 90));
            }
            assert.ok(exempted >= 15,
                'the exemption should cover a large share of the real corpus (measured 21 of ' +
                '67); if this collapses, re-measure before weakening it');
        });

        it('is byte-identical below the gate, every payload', function () {
            for (const payload of CORPUS)
                assert.deepStrictEqual(captureCommands(payload, 'mainnet', 4000000000), [payload]);
        });
    });
});
